# Generated by Django 4.0.4 on 2022-04-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('memo', models.TextField()),
                ('Subject_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='majorapp.major')),
            ],
        ),
    ]
